### ISSUE TITLE
Idea: consider printing a warning when `blueprint_mutex_disabled` is unset

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#126]
The blueprint mutex feature defaults to "enabled" because that's the safe/conservative thing to do. Users must opt-in to the more dangerous operational mode.

But really, users have 3 options:
- explicit enable
- explicit disable
- unset

Maybe we should print a warning (hey! did you know this feature is on?) when the feature is in its un-configured default state.

Should the warning print unconditionally, or only when a lock is asserted (blueprint operations)?

**Comment by chrismarget-j** [comment]
Proposal: Introduce `blueprint_mutex_enabled` mutex (another boolean).

With two booleans covering the same feature we have four options:

- `disabled: false + enabled: false ` this is the default case with no action taken by the user. Enable the mutex feature (it's the safe/conservatice choice) and print a warning about interminable commits and encourage the user to make a choice.
- `disabled: false  + enabled: true ` this user has affirmatively opted in to the mutex feature. No warning.
- `disabled: true  + enabled: false` This user has affirmatively opted out of the mutex feature. No warning.
- `disabled: true  + enabled: true ` Invalid configuration. Error and exit.

**Comment by rajagopalans** [comment]
I get the spirit of it, but we maybe can call it something else?
having 2 flags x_disabled and x_enabled is not intuitive

**Comment by chrismarget-j** [comment]
I talked to Adam a bit today. He had a good idea:

- Use a single boolean to control the locking behavior
- Default to better usability: no locking
- Because the TF booleans support `null`, print a warning (with link to documentation, etc) whenever the setting is found to be unconfigured.

This proposal satisfies my desire to avoid unsafe behavior without attempting mitigation (the warning is the user's chance to bail out) while satisfying the competing desire to streamline adoption by new users.

**Comment by rajagopalans** [comment]
Sounds good.

**Comment by bwJuniper** [comment]
Love it. Glad Adams idea works! seems more simple for sure.
