### ISSUE TITLE
task: eliminate extra checks for `nil` client object

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#140]
All of our CRUD methods have a check like this:

```go
if o.client == nil {
	resp.Diagnostics.AddError(errResourceUnconfiguredSummary, errResourceUnconfiguredCreateDetail)
	return
}
```

These checks came from an early misunderstanding I had about config validation. The resource and datasource `ValidateConfig` methods get called without necessarily having a fully configured provider and I kept running into nil pointer dereference problems when doing validation-related API transactions (these were a bad idea as well).

I responded by putting the nil client check in every method, but it seems the framework won't call any of `Create()`, `Read()`, `Update()` or `Delete()` without first completing provider configuration.

These checks are unnecessary in resource CRUD and in datasource `Read()`, and can be removed, along with the constants which will no longer be needed after the checks are removed.

**Comment by bwJuniper** [comment]
Closed by #199
