### ISSUE TITLE
Configlet Provider Error

### ISSUE THREAD

**Issue by michaelbhughes** [Juniper/terraform-provider-apstra#287]
**Summary**
An error has started appearing with Configlets that we have not seen before. Not sure what changed, but I am seeing a "Value Conversion Error" when trying to plan Configlets. The error texts states this error type is "always an error in the provider", but perhaps I am not giving valid values to the Configlets?. Please take a look at your convenience.

Provider Version: `v0.27.0`
Terraform Version: `1.5.5`

**Error Text**
```sh
│ Error: Value Conversion Error
│ 
│   with module.common.apstra_configlet.configlets,
│ An unexpected error was encountered trying to build a value. This is always
│ an error in the provider. Please report the following to the provider
│ developer:
│ 
│ Received unknown value, however the target type cannot handle unknown
│ values. Use the corresponding `types` package type or a custom type that
│ handles unknown values.
│ 
│ Path: 
│ Target Type: []design.ConfigletGenerator
│ Suggested Type: basetypes.ListValue
```

<br>

**variables.tf**
```hcl
variable "configlets" {
        type = map(object({
            name       = string
            generators = list(object({
                config_style           = string
                section                = string
                template_text          = string
                negation_template_text = optional(string)
            }))
        }))
        description = "Configlets in the Design section of the Apstra server."
        default     = {
        tf_dell_sonic_00_day0_post_login_banner = {
            name    = "tf_dell_sonic_00_day0_post_login_banner"
            generators = [
                {
                    config_style           = "sonic"
                    section                = "file"
                    template_text          = <<-EOT
         PLACEHOLDER
    EOT
                    negation_template_text = <<-EOT
  
    EOT
                }
            ]
        }
        tf_dell_sonic_01_day0_system_config_tlab = {
            name    = "tf_dell_sonic_01_day0_system_config_tlab"
            generators = [
                {
                    config_style           = "sonic"
                    section                = "system"
                    template_text          = <<-EOT
         PLACEHOLDER
    EOT
                    negation_template_text = <<-EOT
         PLACEHOLDER
    EOT
                }
            ]
        }
        tf_dell_sonic_02_day0_tacacs_config_tlab = {
            name    = "tf_dell_sonic_02_day0_tacacs_config_tlab"
            generators = [
                {
                    config_style           = "sonic"
                    section                = "system"
                    template_text          = <<-EOT
         PLACEHOLDER
    EOT
                    negation_template_text = <<-EOT
         PLACEHOLDER
    EOT
                }
            ]
        }
        }
    }
```

**Comment by michaelbhughes** [comment]
Hello, I updated my image with the provider `v0.28.0` and I am still encountering the error. The details of the error are identical.

I tried a few things like changing the syntax of the `template_text` attributes and playing with how I feed values to the apstra_configlet resource, but the same behaviour occurs in every case.

May you please take another look at this issue?

**Comment by rajagopalans** [comment]
Hello, 
@michaelbhughes I was able to test with and without the latest provider. It seems to work.
I am happy to sync up in the morning tomorrow to look at your config and see how the error is triggered.

rsubrahmania@rsubrahmania-mbp test % terraform -version
Terraform v1.5.5
on darwin_amd64
+ provider registry.terraform.io/juniper/apstra v0.25.1
rsubrahmania@rsubrahmania-mbp test % terraform plan
╷
│ Error: Value Conversion Error
│ 
│   with apstra_configlet.r,
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Received unknown value, however the target type cannot handle unknown values. Use the corresponding `types` package type or a custom type that handles unknown values.
│ 
│ Path: 
│ Target Type: []design.ConfigletGenerator
│ Suggested Type: basetypes.ListValue
╵

rsubrahmania@rsubrahmania-mbp test % terraform -version
Terraform v1.5.5
on darwin_amd64
+ provider registry.terraform.io/juniper/apstra v0.28.1
rsubrahmania@rsubrahmania-mbp test % terraform plan
data.apstra_configlet.cfg: Reading...
data.apstra_configlet.cfg: Read complete after 1s [id=US-MOTD]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # apstra_configlet.example will be created
  + resource "apstra_configlet" "example" {
      + generators = [
          + {
              + config_style  = "junos"
              + section       = "top_level_hierarchical"
              + template_text = <<-EOT
                    name-server {
                      4.2.2.1;
                      4.2.2.2;
                    }
                EOT
            },
          + {
              + config_style           = "eos"
              + negation_template_text = "no ip name-server 4.2.2.1 4.2.2.2"
              + section                = "system"
              + template_text          = "ip name-server 4.2.2.1 4.2.2.2"
            },
        ]
      + id         = (known after apply)
      + name       = "DNS according to Terraform"
    }

  # apstra_configlet.r will be created
  + resource "apstra_configlet" "r" {
      + generators = [
          + {
              + config_style           = "sonic"
              + negation_template_text = <<-EOT
                    PLACEHOLDER
                EOT
              + section                = "system"
              + template_text          = <<-EOT
                    PLACEHOLDER
                EOT
            },
        ]
      + id         = (known after apply)
      + name       = "tf_dell_sonic_01_day0_system_config_tlab"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
rsubrahmania@rsubrahmania-mbp test %

**Comment by rajagopalans** [comment]
@michaelbhughes I just noticed that I used 0.28.1 
Please try that one as well, I believe there was a dot release between when you tried and when I tried.
that should do it.
thanks

**Comment by michaelbhughes** [comment]
Trying `v0.28.1` this morning; will get back to you on the result soon 👍

**Comment by michaelbhughes** [comment]
The error is gone with `v0.28.1` 👍 Thank you for the support. Feel free to close this issue if all is good on your end.

**Comment by chrismarget-j** [comment]
Right on, thank you for following up, @michaelbhughes.
