### ISSUE TITLE
File needs to be renamed

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#413]
`apstra/resource_connectivity_template_assignment.go` should probably be `apstra/resource_datacenter_connectivity_template_assignment.go`

**Comment by bwJuniper** [comment]
What are the dependencies? I renamed the file but is there some other steps?

**Comment by chrismarget-j** [comment]
As long as the file stays in the same directory, Go won't care.

Best way to do this is with `git mv old_name new_name`

Using `git mv` rather than just `mv` ensures that git recognizes the change is only a name change, rather than a deletion and an unrelated new file.
