### ISSUE TITLE
Small changes to docs organization for provider 

### ISSUE THREAD

**Issue by bwJuniper** [Juniper/terraform-provider-apstra#419]
Update "Resources" to "resource pools".
Update "RefDesign: Any" to "RefDesign: Shared"

**Comment by rajagopalans** [comment]
I was thinking about this, should we call this something other than RefDesign?
It's camelcased, and seems to be a no-no in terraform.
Is RefDesign a term of art in Apstra?
If not, can we rename this to reference_design or ReferenceDesign? RefDesign seems a little too inside baseball
@bwJuniper  @chrismarget-j

**Comment by chrismarget-j** [comment]
> inside baseball

Well said. I was thinking the same thing.

Apstra definitely presents some variant of this term, but we should sniff around the GUI and docs to see what the "right" version is.

Human readable seems to be the approach for this field: Before we started moving things around, we had "Resources" and "Data Sources", so I'm leaning toward "Reference Design".

Also, "Resource Pools", which I'm a little less happy about (the left sidebar in Apstra just says "Resources", but everything under there is some flavor of pool, and the confusing collision with terraform's "Resources" is worse than the slight deviation from the GUI's nomenclature in my opinion.

**Comment by rajagopalans** [comment]
@bwjuniper, you got any ideas for the nomenclature?

**Comment by chrismarget-j** [comment]
closed by #422
