### ISSUE TITLE
Add import/export RTs to virtual network resource/datasources

### ISSUE THREAD

**Issue by coterv** [Juniper/terraform-provider-apstra#428]
Inclusion of import/export RT policies in the resource 'apstra_datacenter_virtual_network,' mirroring the addition made to 'apstra_datacenter_routing_zone' as a response to issue https://github.com/Juniper/terraform-provider-apstra/issues/406.

(I apologize for not mentioning this earlier and for requesting both additions separately).

**Comment by chrismarget-j** [comment]
Note to myself: import/export RT shows up in the GUI when you select type: "VXLAN"
