### ISSUE TITLE
Error "staging is not synced with config" when adding generic systems to leaf switch breakout ports

### ISSUE THREAD

**Issue by michaelbhughes** [Juniper/terraform-provider-apstra#444]
## Summary
An strange issue has been appearing intermittently in our development environment. When adding generic systems via the terraform `apstra_datacenter_generic_system` resource, any generic systems with links to leafs where the leaf port needs to be broken-out from 1x100G to 4x25G fails to be added with the error below.

```bash
│ Error: failed to create generic system
│ 
│   with apstra_datacenter_generic_system.external_generic_system["HV-002"],
│   on resource.tf line 58, in resource "apstra_datacenter_generic_system" "external_generic_system":
│   58: resource apstra_datacenter_generic_system external_generic_system {
│ 
│ {"api_response":null,"config_blueprint_version":0,"errors":{"_schema":"Staging
│ is not synced with config"},"error_code":422} - http response '' at
│ '[http://10.17.170.4/api/blueprints/4b7a8933-b4c9-4ece-ad2f-edf7fea8e2ec/switch-system-links?async=full&async=full'](http://10.17.170.4/api/blueprints/4b7a8933-b4c9-4ece-ad2f-edf7fea8e2ec/switch-system-links?async=full&async=full%27)
╵
```

Generic systems connected to access switch ports do not have this error, and these ports are not breakouts. The error only appears on leaf ports that need breakouts.

The following workaround worked once, but now no longer works.
> 1. If the error occurs, continue with overlay resources configs and make a commit that will update configs on physical devices; fabric should deploy fully without issues
> 2. Manually comment-out generic systems in terraform code
> 4. Run destroy plan and apply jobs for overlay resources so we can remove existing generic systems
> 5. Run underlay plan and apply to remove existing generic systems (current generic systems are only on access switches, none are on leafs)
> 6. Manually re-add generic systems in terraform code
> 8. Run underlay plan and apply to re-add existing generic systems
> 9. Continue with the rest of the jobs to finish configuring and deploying the fabric

Because the workaround above no longer works, I cannot finish adding generic systems to my development fabrics. The strange thing is on a much larger fabric in my preproduction environment with 97 generic systems, I did not encounter this error; this error has only appeared on a fabric with 13 generic systems.

More details on this error are directly below and under the Details heading further down.

- Deleting the blueprint fully and starting from scratch does not resolve the issue.
- Undeploying the fabric devices and deploying them again also does not resolve the issue.

## Details
Here are some screenshots and outputs from the Apstra GUI for the tasks that failed when trying to add the generic systems.

1. All failed tasks
![image](https://github.com/Juniper/terraform-provider-apstra/assets/97752342/0c685933-3af8-4713-9265-c1e954d2abc3)

2. One of the failed tasks
![image](https://github.com/Juniper/terraform-provider-apstra/assets/97752342/6d354888-bd65-4664-83ad-44ea8dffe331)

3. Detailed status of the failed task
![image](https://github.com/Juniper/terraform-provider-apstra/assets/97752342/a42dac7f-d626-4320-829b-471c011737ce)

4. Request data for the failed task
```json
{
  "url": "http://10.17.170.4/api/blueprints/1b4c2cbb-e190-4917-b2e7-d9a18cf18e2a/switch-system-links?async=full",
  "headers": {
    "X-Forwarded-Proto": "https",
    "Accept": "application/json",
    "Accept-Encoding": "gzip",
    "X-Forwarded-For": "172.21.206.102",
    "X-User": "admin",
    "X-User-Id": "0508a8a7-4864-483a-89ae-6476c938b302",
    "X-Real-Ip": "172.21.206.102",
    "Content-Length": "2517",
    "Host": "10.17.170.4",
    "Connection": "close",
    "Content-Type": "application/json",
    "User-Agent": "Go-http-client/1.1"
  },
  "args": {
    "async": "full"
  },
  "data": {
    "new_systems": [
      {
        "hostname": "EDTNABTF-PD12HV-003",
        "port_channel_id_min": 0,
        "tags": [
          "BM",
          "HV",
          "Server"
        ],
        "port_channel_id_max": 0,
        "label": "HV-003",
        "system_type": "server",
        "logical_device": {
          "panels": [
            {
              "panel_layout": {
                "row_count": 1,
                "column_count": 1
              },
              "port_indexing": {
                "order": "T-B, L-R",
                "start_index": 1,
                "schema": "absolute"
              },
              "port_groups": [
                {
                  "count": 1,
                  "speed": {
                    "unit": "M",
                    "value": 100
                  },
                  "roles": []
                }
              ]
            }
          ],
          "display_name": "TF LD template",
          "id": "tf-ld-template"
        }
      }
    ],
    "links": [
      {
        "switch": {
          "transformation_id": 3,
          "system_id": "sDo_G6r2fJ436kJJcAs",
          "if_name": "Ethernet14"
        },
        "link_group_label": "bond1",
        "system": {
          "system_id": null
        },
        "lag_mode": "lacp_active",
        "tags": [
          "BM",
          "HV",
          "HV-003",
          "Resource_02",
          "ST-worker",
          "Server",
          "bird",
          "ens2f0"
        ]
      },
      {
        "switch": {
          "transformation_id": 3,
          "system_id": "-Y1IwKPesYPurUbZLLY",
          "if_name": "Ethernet14"
        },
        "link_group_label": "bond1",
        "system": {
          "system_id": null
        },
        "lag_mode": "lacp_active",
        "tags": [
          "BM",
          "HV",
          "HV-003",
          "Resource_02",
          "ST-worker",
          "Server",
          "bird",
          "ens2f1"
        ]
      },
      {
        "switch": {
          "transformation_id": 3,
          "system_id": "sDo_G6r2fJ436kJJcAs",
          "if_name": "Ethernet15"
        },
        "link_group_label": "bond2",
        "system": {
          "system_id": null
        },
        "lag_mode": "lacp_active",
        "tags": [
          "BM",
          "HV",
          "HV-003",
          "Resource_02",
          "ST-worker",
          "Server",
          "ens3f0",
          "macvlan"
        ]
      },
      {
        "switch": {
          "transformation_id": 3,
          "system_id": "-Y1IwKPesYPurUbZLLY",
          "if_name": "Ethernet15"
        },
        "link_group_label": "bond2",
        "system": {
          "system_id": null
        },
        "lag_mode": "lacp_active",
        "tags": [
          "BM",
          "HV",
          "HV-003",
          "Resource_02",
          "ST-worker",
          "Server",
          "ens3f1",
          "macvlan"
        ]
      },
      {
        "switch": {
          "transformation_id": 3,
          "system_id": "sDo_G6r2fJ436kJJcAs",
          "if_name": "Ethernet12"
        },
        "link_group_label": "bond_infra",
        "system": {
          "system_id": null
        },
        "lag_mode": "lacp_active",
        "tags": [
          "BM",
          "HV",
          "HV-003",
          "PXE",
          "Resource_02",
          "ST-worker",
          "Server",
          "bond_infra",
          "ens10f0np0"
        ]
      },
      {
        "switch": {
          "transformation_id": 3,
          "system_id": "-Y1IwKPesYPurUbZLLY",
          "if_name": "Ethernet12"
        },
        "link_group_label": "bond_infra",
        "system": {
          "system_id": null
        },
        "lag_mode": "lacp_active",
        "tags": [
          "BM",
          "HV",
          "HV-003",
          "Resource_02",
          "ST-worker",
          "Server",
          "bond_infra",
          "ens10f1np1"
        ]
      },
      {
        "switch": {
          "transformation_id": 3,
          "system_id": "sDo_G6r2fJ436kJJcAs",
          "if_name": "Ethernet13"
        },
        "link_group_label": "bond_pf",
        "system": {
          "system_id": null
        },
        "lag_mode": "lacp_active",
        "tags": [
          "BM",
          "HV",
          "HV-003",
          "Resource_02",
          "ST-worker",
          "Server",
          "bond_pf",
          "ens1f0"
        ]
      },
      {
        "switch": {
          "transformation_id": 3,
          "system_id": "-Y1IwKPesYPurUbZLLY",
          "if_name": "Ethernet13"
        },
        "link_group_label": "bond_pf",
        "system": {
          "system_id": null
        },
        "lag_mode": "lacp_active",
        "tags": [
          "BM",
          "HV",
          "HV-003",
          "Resource_02",
          "ST-worker",
          "Server",
          "bond_pf",
          "ens1f1"
        ]
      }
    ]
  },
  "method": "POST"
}

```

**Comment by michaelbhughes** [comment]
Created JTAC case for this issue: https://supportportal.juniper.net/s/case/500Dp00000CyUggIAF/error-staging-is-not-synced-with-config-when-adding-generic-systems-to-blueprint-via-terraform

**Comment by michaelbhughes** [comment]
This issue no longer appears in Apstra `4.2.0` or in `4.1.2` when we update the cable map programmatically instead of manually via the GUI. JTAC provided a great explanation for what the error actually means, copied below.

Although we did not find the root cause, we suspect it was due to errors manually updating the cable map via the GUI (e.g. typing in an invalid EthernetX value for an interface).

In the interest of time, we are moving on from this issue. We can reopen this issue if we run into the error again in the future.

> We have come up with a probable reasoning on “Staging is not synced with config” error while trying to “broken-out” from 1x100G to 4x25G on a leaf node towards an existing generic system using terraform. It could be the Transformation ID lets say for Interface Names i.e “if_name” which are created while an existing port is being broken to lower speed transformation is not validated and they are not consistent between Config and Staging database for an Apstra Blueprint. This should be the reason for the exception being generated and the reason why they are not valid could be due to inconsistency in the “if_name” etc or anything like that when a resource is being created via terraform. As part of day 2 operation when you break-out an existing port a new Interface Map with correct transformations of “if_name” is generated and those should be failing in validation as per the backend code in this case. To elaborate more let say when you break out a 100 gig interface into 4 x 25 gig ports one of the Interface Name may be missing in the resource file or given incorrectly or names overlapping and not distinct enough or a timing issue between various API calls from Terraform resulting in inconsistent Transformation IDs for Interface being broken out.
> 
> This could be another reason while you update the cable map programmatically using the API call Interface Names are set accordingly as per the transformation and now it doesn't break in validation.
> 
> Please note that the configuration database is built from any changes done by the user in the Apstra UI. Staging database is derived dynamically from the configuration database. In case there is inconsistency with respect to Interface Name transformations in Interface Map for staging and configuration databases such as if “if_name” does exist in staging but is there in the config database such exceptions will be raised.

**Comment by michaelbhughes** [comment]
JTAC provided the following notes on what may be causing this error @chrismarget-j 

> If you are creating and assigning the generic system (link creation between the device and generic system) on the same round, I also would like to ask you to check the possibility of adding a delay between generic system creation and assigned tasks, to make sure that each generic system is already created and ready to be assigned (link creation) on the stage before assign. Also for the generic systems assigned to the same device, try to assign them sequentially not parallel.

**Comment by michaelbhughes** [comment]
@chrismarget-j Latest JTAC reply is copied below.

> Escalation has confirmed with your cable map json file that there are 'if_name' fields which has empty strings (i.e. "if_name": "") causing the "Staging is not synced with config" error. This is the current expected behavior. You should use 'null' instead of "" value to avoid the error. 

The fine print is that the .json cable map that my pipeline uploaded to the Apstra API only has empty strings in the if_name attribute for Generic Systems; the internal fabric links are all good, no empty strings. Here is one of my comments explaining what I see.

> Case 1: Pipeline works the first time
> The "Staging is not synced with config"  error does not appear because the downloaded cable map that was manipulated by my code did not have generic systems in it yet, only spines, leafs, and access switches. So there were no instances of the if_name attributes with empty strings at this time. Therefore, the pipeline worked and did not trigger the error.

> Case 2: Pipeline fails once and we rerun it
> Let's say the pipeline failed at some point after adding a few generic systems (this is what has happened here). When I adjust my code and rerun the pipeline, it downloads the latest copy of the cable map which now includes some generic systems with the empty if_name attributes. My code manipulates the downloaded cable map without issue, and uploads it without issue, but when we move on to adding more generic systems, Apstra notices the attributes with empty strings and throws the "Staging is not synced with config" error. And now we are stuck in a bad state that we cannot get out of.

With this in mind, I do not believe I can control how the if_name attribute is set in the cable map for generic systems on my end. So I wanted to see if you can edit the provider to set if_name attributes to null instead of empty strings for generic systems without device profiles.

Maybe the `apstra_datacenter_generic_system` resource's code can be edited to do this? Or maybe I will have to engineer an add-on to my cable map update code to change all instance of "if_name": "" to "if_name": null?

Please let me know your thoughts on this.

**Comment by michaelbhughes** [comment]
@chrismarget-j I actually think it is not difficult to overwrite the generic system link if_name attributes on my end, I am going to give it a shot. Please do provides your thoughts in the mean time :)

**Comment by chrismarget-j** [comment]
Broadly speaking, the difference between {“if_name”: null} and {“if_name”: “”} can be important, so clients must be able to send one or the other as appropriate.

It’s probably not important that we be able to express both conditions to the Apstra API (only one of them is useful!), but that’s the way they’ve implemented it, I guess.

We have to deal with this kind of thing in our code all the time. Go has levers for controlling the client behavior, I imagine your tooling does too.

Good luck?

/chris



Juniper Business Use Only
From: Michael Hughes ***@***.***>
Date: Tuesday, December 5, 2023 at 2:47 PM
To: Juniper/terraform-provider-apstra ***@***.***>
Cc: Chris Marget ***@***.***>, Mention ***@***.***>
Subject: Re: [Juniper/terraform-provider-apstra] Error "staging is not synced with config" when adding generic systems to leaf switch breakout ports (Issue #444)
[External Email. Be cautious of content]


@chrismarget-j<https://urldefense.com/v3/__https:/github.com/chrismarget-j__;!!NEt6yMaO-gk!HDAdbxzKiTOIjsUoTzZovopKcTj49dk9P-6nqXnWZdluTfKZVRZ5_YPmzeVUc954MqFLMq5Ck-cj_FqA0DIEgZml$> I actually think it is not difficult to overwrite the generic system link if_name attributes on my end, I am going to give it a shot. Please do provides your thoughts in the mean time :)

**Comment by michaelbhughes** [comment]
@chrismarget-j Good news! I found the issue, and man is it simple... The template I use has a section for links that we do not want to change, and it just copies over the values that the downloaded cable map had. If the if_name that was being copied had a value, the code worked. But if the value was null, then if_name would be set to `""` due to the original value being null. I introduced a conditional to handle the case when if_name is null, see below.

**Before**
`"if_name": "{{ actual_link.endpoints[0].interface.if_name }}"`

**After**
`"if_name": {% if actual_link.endpoints[0].interface.if_name is none %}"{{ actual_link.endpoints[0].interface.if_name }}"{% else %}null{% endif %}`

Glad we were able to identify what the root cause of the issue was. And the root cause was that the cable map template that I wrote changed null if_name values to empty strings instead of preserving the null value.

Feel a little dumb for spending so much time troubleshooting this bug and having it be such a simple thing... but I am glad it is fixed now :)

Thanks for the support @chrismarget-j. I am going to close this issue (hopefully for the last time!).
