### ISSUE TITLE
Add L3 MTU attribute to resource apstra_datacenter_virtual_network

### ISSUE THREAD

**Issue by coterv** [Juniper/terraform-provider-apstra#499]
Add L3 MTU attribute to resource apstra_datacenter_virtual_network (available from AOS 4.2.0)

**Comment by chrismarget-j** [comment]
[SDK #182](https://github.com/Juniper/apstra-go-sdk/pull/182) was created to support this requirement.

As it stands now, the new `l3_mtu` attribute behavior will look like:

| Apstra version | use case | behavior | notes |
| --- | --- | --- | --- |
| <4.2.0 | resource `apstra_datacenter_virtual_network` | computed optional | error in apply phase when not `null` |
| <4.2.0 | data `apstra_datacenter_virtual_network` | computed | always `null` |
| <4.2.0 | data `apstra_datacenter_virtual_networks` (used as filter) | optional | warn that filter will never match when not `null` |
| >=4.2.0 | resource `apstra_datacenter_virtual_network` | computed optional | sets VN attribute |
| >=4.2.0 | data `apstra_datacenter_virtual_network` | computed | always reports VN attribute value |
| >=4.2.0 | data `apstra_datacenter_virtual_networks` (used as filter) | optional | filters VNs via graph query |
