### ISSUE TITLE
Setting Generic System port names

### ISSUE THREAD

**Issue by coterv** [Juniper/terraform-provider-apstra#520]
Hello,

We need to ensure the accurate naming of Generic System ports when associating each interface assignment from Generic System A port B to Leaf C port D. This ensures that the precise names of Generic System interfaces are mirrored in Apstra and consequently reflected in the descriptions of the Generic System-facing interfaces in the Leaf configurations.

As far as I can discern, there are two feasible approaches to configuring them in Apstra:
 
Option A: Construct the Generic System solely based on a Logical Device (without binding to a specific Device Profile in the Interface Map).
 
In this approach, Apstra doesn't automatically assign a port name, making it ineligible for naming when establishing links to the leafs. To rectify this, the next step involves editing the Cabling Map to assign port names to the Generic System.
 
Is it possible to perform this Cabling Map editing through Terraform?
 
On a related note, I noticed from Chris' comments in the Teams Channel that the resource "apstra_datacenter_generic_system" lacks an attribute to allocate a particular Logical Device to a Generic System. The reasoning behind this omission is that selecting a Logical Device has no impact; even in the GUI, seemingly impossible cabling choices are allowed. It's essentially a no-op choice.
 
Option B: Form the Generic System based on an Interface Map (binding a Logical Device to a Device Profile) with appropriate port naming to obviate the need for later Cabling Map editing.
 
Currently, assigning Interface Maps to the "apstra_datacenter_generic_system" resource isn't available in the provider. There's an open Github issue (Ticket #466) to address this limitation.
 
Even if this becomes possible shortly, the out-of-the-box Device Profile catalog lacks valid profiles with the necessary port names for modeling both servers (ensXfY nomenclature) and Cisco/Juniper devices (modular devices with high port numbers). Creating new Device Profiles may be a solution, potentially using the "apstra_modular_device_profile" resource (though it's unclear if exact port naming rules are configurable), but, as discussed last week, there's currently no native way to retrieve the ID of a Device Profile via any data object, preventing us from associating it with a Logical Device when creating the Interface Map.
 
My initial impression is that Option B may not be the most practical due to various pitfalls, making Option A potentially more convenient.
 
I would highly value your guidance on this matter, particularly if you have faced similar challenges in the past. This will enable us to adopt the most appropriate strategy to address this issue.

Thanks in advance.

**Comment by coterv** [comment]
Temporary workaround deployed via API using Python scripts to fetch, modify and upload the cabling map. Happy to share with any interested stakeholders.

**Comment by chrismarget-j** [comment]
We don't plan to support Device Profile association (via Interface Map) for generic systems.

**Comment by ciroiriarte** [comment]
Is there a way to support interface labels via any other route?, it would greatly improve documentation and troubleshooting

**Comment by chrismarget-j** [comment]
> Is there a way to support interface labels via any other route?

I'm not sure what you mean by interface labels. A screenshot of the GUI indicating the kind of thing you'd like to modify would help.

**Comment by ciroiriarte** [comment]
> > Is there a way to support interface labels via any other route?
> 
> I'm not sure what you mean by interface labels. A screenshot of the GUI indicating the kind of thing you'd like to modify would help.

With Chassis/Linecard profiles + interface maps, I was able to model a server with the port information that would allow basic validation without resorting to spreadsheets. This was done manually.

![Image](https://github.com/user-attachments/assets/cb147044-a80b-438a-a361-e788711ab61d)

The attribute I'm after is called "label" in the web UI:

![Image](https://github.com/user-attachments/assets/bc65d092-969a-4195-a297-cf16c7d1fe85)

I would love to be able to document similarly via the Terraform Provider. All I get now is:

![Image](https://github.com/user-attachments/assets/880b5092-7f81-48dc-8128-58e9555cd30a)

**Comment by chrismarget-j** [comment]
Ah. I understand what you mean by "interface labels" now.

As far as I'm aware, the only way to get meaningful names/labels associated with generic system interfaces is to create a Device Profile and associate it with the Generic System by applying an Interface Map.

There are no plans to add support for doing that via the Terraform provider.

**Comment by coterv** [comment]
Hi Ciro,

We encountered the same issue mentioned at the beginning of this thread, and as a solution, we developed a set of Python scripts to interact with Apstra via API. These scripts [fetch the cabling map](https://ps-network-automation.visualstudio.com/Apstra_Provisioning_Automation_Framework/_git/APAF?path=/tools/python/apstra_pull_cabling_maps.py) from the blueprint, [modify it](https://ps-network-automation.visualstudio.com/Apstra_Provisioning_Automation_Framework/_git/APAF?path=/tools/python/apstra_update_cabling_maps.py) according to our desired interface labels for servers, and then [upload it back](https://ps-network-automation.visualstudio.com/Apstra_Provisioning_Automation_Framework/_git/APAF?path=/tools/python/apstra_push_cabling_maps.py) to Apstra.

What makes this work smoothly is the integration of Python scripts within Terraform. By defining resources of type `terraform_data`, we can execute these scripts based on certain conditions, such as any changes to the data of generic systems or spines. [Here's an example](https://ps-network-automation.visualstudio.com/Apstra_Provisioning_Automation_Framework/_git/APAF?path=/tools/terraform/modules/blueprints/bp_cabling_map.tf) of how we trigger this:

```hcl
resource "terraform_data" "update_cabling_maps_trigger" {
  count = local.blueprint_list != null ? 1 : 0
  input = concat(
    local.flattened_generic_systems,
    local.flattened_spines
  )
}
resource "terraform_data" "update_cabling_maps" {
  count = local.blueprint_list != null ? 1 : 0
  lifecycle {
    replace_triggered_by = [
      terraform_data.update_cabling_maps_trigger
    ]
  }
  depends_on = [
    apstra_datacenter_generic_system.generic_systems,
  ]

  provisioner "local-exec" {
    command = "python3 ../python/apstra_update_cabling_maps.py pull_cabling_maps push_cabling_maps"
    # command = "python3 ../python/apstra_update_cabling_maps.py pull_cabling_maps push_cabling_maps --internal_ips=${local.keep_internal_ips}"
  }
}
```
This is part of a larger framework we've implemented, called the **Apstra Provisioning Automation Framework (APAF)**. You can learn more about this initiative through the following links (or feel free to reach out directly to me if you'd like more details):

- [The introductory Teams channel post](https://teams.microsoft.com/l/message/19:5d04eef9af2f417785d7b0f60832f63b@thread.tacv2/1726476487664?tenantId=bea78b3c-4cdb-4130-854a-1d193232e5f4&groupId=8a3daa9b-0199-4668-a81c-a2041f5c9c3b&parentMessageId=1726476487664&teamName=DC%20GTM%20Lounge&channelName=Go%20and%20Terraform&createdTime=1726476487664)
- [The Git repository in Azure DevOps](https://ps-network-automation.visualstudio.com/Apstra_Provisioning_Automation_Framework/_git/APAF)
- [The Wiki](https://ps-network-automation.visualstudio.com/Apstra_Provisioning_Automation_Framework/_wiki/wikis/Apstra-Provisioning-Automation-Framework.wiki/222/Framework-Overview)
- [Poster and video recordings from the Spark Junivator Innovation Summit 2024](https://junipernetworks.sharepoint.com/sites/SparkExpoHall2024/SitePages/Apstra-Provisioning-Automation-Framework.aspx)
- [Another Teams channel post about setting up a containerized version of APAF](https://teams.microsoft.com/l/message/19:5d04eef9af2f417785d7b0f60832f63b@thread.tacv2/1737478582794?tenantId=bea78b3c-4cdb-4130-854a-1d193232e5f4&groupId=8a3daa9b-0199-4668-a81c-a2041f5c9c3b&parentMessageId=1737478582794&teamName=DC%20GTM%20Lounge&channelName=Go%20and%20Terraform&createdTime=1737478582794)

Thanks in advance.

**Comment by ciroiriarte** [comment]
> apstra_update_cabling_maps.py

Hey Carlos, thanks for the tip. Initially, it looks spooky :)

Any change for you to share apstra_update_cabling_maps.py?
