### ISSUE TITLE
Introduce `null_when_notfound` boolean attribute to `apstra_datacenter_system` data source

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#523]
The `apstra_datacenter_system` data source requires the user to specify either the id or name (label) of a graphDB `system` node.

If no matching node is found, the data source logs an error and terraform execution stops.

We should introduce a user-controllable switch: When set, the data source will not raise an error, but rather set all of its outputs to `null`

**Comment by bwJuniper** [comment]
default behavior to mirror  current behavior
lets call it "null_when_not_found"
