### ISSUE TITLE
Should IBA probe/widget/dashboard resources be locking the blueprint?

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#546]
I noticed today that these resources don't lock the blueprint.

- `apstra_blueprint_iba_dashboard`
- `apstra_blueprint_iba_probe`
- `apstra_blueprint_iba_widget`

I have some vague recollection that this is the correct/expected behavior, but I don't remember what that is and I'm surprised to find that it applies to three different resources.

Raj, can you please refresh my memory on this?

**Comment by rajagopalans** [comment]
Blueprint lockng is required for changes made to the "staged" area.
The iba related stuff is outside of that, while still being in the blueprint.
So, locking is not required.

**Comment by rajagopalans** [comment]
[locking the blueprint applies when a commit step is required. 
](https://www.juniper.net/documentation/us/en/software/apstra/apstra3.3.0/managing_roles.html)

Per this, anything that requires a commit will trigger locking
