### ISSUE TITLE
Feature Request - Statically Allocate BGP peering IPs (similar to #562)

### ISSUE THREAD

**Issue by fengwang523** [Juniper/terraform-provider-apstra#563]
This request is similar to #562 

For border leaf BGP peering sessions with generic system, the same challenge applies.

 The BGP peering IPs are allocated by a role "to_generic_link_ips" to an IP pool mapping.  Here is an example code:

resource "apstra_datacenter_resource_pool_allocation" "tf_rz_ipv4_external_allocation" {
  count   = var.rz_ipv4_external_pool != null ? 1 : 0
  blueprint_id = var.bp_id
  role         = "to_generic_link_ips"
  pool_ids     = [apstra_ipv4_pool.tf_rz_ipv4_external_pool[0].id]
  routing_zone_id = apstra_datacenter_routing_zone.tf_rz.id
}

The peering IPs are dynamically allocated, therefore the values are not known until terraform apply and they would change upon destroy and re-apply.

The feature request is that to be able to hardcode the peering IPs using values from the IP pool.

**Comment by chrismarget-j** [comment]
Much of the discussion in #562 applies here.

Also of interest is the `apstra_datacenter_ip_link_addressing` resource introduced with v0.60.0, which can be used to assign IPs to Generic Systems configured to use "IP Link" Connectivity Templates (this use case, I think).
