### ISSUE TITLE
Assign IP addresses to IP Link CT Primitive

### ISSUE THREAD

**Issue by coterv** [Juniper/terraform-provider-apstra#581]
When assigning a CT with IP Link primitives to application points, p2p links are automatically created within each applicable RZ and the resource pool Link IPs - To Generics is used to dynamically allocate the IP endpoints (/31) on each side of the link.

These /31 IPs can be manually set in the GUI. We need that same behaviour via Terraform, in order to assign predictable IP addressing to those links.

Note: More than one IP link primitive can exist within the same CT, and some of them can refer to the same RZ.

**Comment by coterv** [comment]
Temporary workaround deployed via API using Python scripts. Happy to share with any interested stakeholders.

**Comment by chrismarget-j** [comment]
Closed by #700 and #701.

With provider version 0.60.0 we now have the `apstra_datacenter_ip_link_addressing` resource, and the `apstra_datacenter_connectivity_template_assignments` and `apstra_datacenter_connectivity_templates_assignment` resources now have the `ip_link_ids` read-only attribute.
