### ISSUE TITLE
can't create blueprint with 0.52.4

### ISSUE THREAD

**Issue by viets2k** [Juniper/terraform-provider-apstra#586]
Hi Chris,

I've some trouble creating blueprint towards Apstra 4.2.0 and 4.2.1. I'm using version 0.52.4. The code is your example from: https://registry.terraform.io/providers/Juniper/apstra/latest/docs/resources/blueprint_deployment

<pre>
# This example instantiates a blueprint from a template,
# allocates IPv4 and ASN resource pools to template roles
# and deploys the template.

# Instantiate a blueprint from a template
resource "apstra_datacenter_blueprint" "instantiation" {
  name        = "terraform commit example"
  template_id = "L2_Virtual_EVPN"
}

# ASN pools, IPv4 pools and switch devices will be allocated using looping
# resources. These three `local` maps are what we'll loop over.
locals {
  asn_pools = {
    spine_asns = ["Private-64512-65534"]
    leaf_asns  = ["Private-4200000000-4294967294"]
  }
  ipv4_pools = {
    spine_loopback_ips  = ["Private-10_0_0_0-8"]
    leaf_loopback_ips   = ["Private-10_0_0_0-8"]
    spine_leaf_link_ips = ["Private-10_0_0_0-8"]
  }
  switches = {
    spine2               = "Juniper_vQFX__AOS-7x10-Spine"
    spine1               = "Juniper_vQFX__AOS-7x10-Spine"
    l2_virtual_001_leaf1 = "Juniper_vQFX__AOS-7x10-Leaf"
    l2_virtual_002_leaf1 = "Juniper_vQFX__AOS-7x10-Leaf"
    l2_virtual_003_leaf1 = "Juniper_vQFX__AOS-7x10-Leaf"
    l2_virtual_004_leaf1 = "Juniper_vQFX__AOS-7x10-Leaf"
  }
}

# Assign interface maps to fabric roles to eliminate build errors so we
# can deploy
resource "apstra_datacenter_device_allocation" "interface_map_assignment" {
  for_each         = local.switches
  blueprint_id     = apstra_datacenter_blueprint.instantiation.id
  node_name        = each.key
  initial_interface_map_id = each.value
}

# Assign ASN pools to fabric roles to eliminate build errors so we
# can deploy
resource "apstra_datacenter_resource_pool_allocation" "asn" {
  for_each     = local.asn_pools
  blueprint_id = apstra_datacenter_blueprint.instantiation.id
  role         = each.key
  pool_ids     = each.value
}

# Assign IPv4 pools to fabric roles to eliminate build errors so we
# can deploy
resource "apstra_datacenter_resource_pool_allocation" "ipv4" {
  for_each     = local.ipv4_pools
  blueprint_id = apstra_datacenter_blueprint.instantiation.id
  role         = each.key
  pool_ids     = each.value
}

# The only required field for deployment is blueprint_id, but we're ensuring
# sensible run order and setting a custom commit message.
resource "apstra_blueprint_deployment" "deploy" {
  blueprint_id = apstra_datacenter_blueprint.instantiation.id

  #ensure that deployment doesn't run before build errors are resolved
  depends_on = [
    apstra_datacenter_device_allocation.interface_map_assignment,
    apstra_datacenter_resource_pool_allocation.asn,
    apstra_datacenter_resource_pool_allocation.ipv4,
  ]

  # Version is replaced using `text/template` method. Only predefined values
  # may be replaced with this syntax. USER is replaced using values from the
  # environment. Any environment variable may be specified this way.
  comment      = "Deployment by Terraform {{.TerraformVersion}}, Apstra provider {{.ProviderVersion}}, User $USER."
}
</pre>

I get the following error, cutted:
<pre>
apstra_datacenter_blueprint.instantiation: Creating...
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for apstra_datacenter_blueprint.instantiation.access_switch_count. All values must be known after apply, so this is always a bug in the provider and should be reported in the provider's own
│ repository. Terraform will still save the other known object values in the state.
╵
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for apstra_datacenter_blueprint.instantiation.build_errors_count. All values must be known after apply, so this is always a bug in the provider and should be reported in the provider's own
│ repository. Terraform will still save the other known object values in the state.
...
</pre>

hope this help and you can have a look.

Thanks in advance
Viets2k

**Comment by chrismarget-j** [comment]
This kind of thing is expected with Apstra 4.2.1, but shouldn't be happening with 4.2.0. Is it happening with both Apstra versions?

**Comment by viets2k** [comment]
in 4.2.0-236 it's also not working, but error is different:

<pre>
╷
│ Error: Blueprint has build errors
│
│   with apstra_blueprint_deployment.deploy,
│   on main.tf line 62, in resource "apstra_blueprint_deployment" "deploy":
│   62: resource "apstra_blueprint_deployment" "deploy" {
│
│ Blueprint "512d63c9-c805-45b7-9dbe-05ea59cd988b" has 8 build errors which must be resolved prior to deployment
</pre>

**Comment by viets2k** [comment]
The blueprint ist create in 4.2.0 and 4.2.1 but it ran into an error.

**Comment by chrismarget-j** [comment]
Ah. This makes sense.

First, the 4.2.0 "Blueprint has build errors" thing:

The `apstra_blueprint_deployment` resource doesn't really "create" anything, it's more of a "click the 🚀 button on the Uncommitted tab" resource. It causes Apstra to deploy the configuration to your devices.

You'll find the same condition in the GUI: Some detail of the staged configuration is incomplete/incompatible (build error) and requires attention before the staging blueprint can be pushed to your devices.

The underlying issue could come down to any number of things like missing resource pool assignments, no switch assigned to some fabric role, etc...

When the GUI indicates "build errors" (uncommitted -> build errors), it won't let you push the button, and Terraform isn't allowed to push the button either.

Because of the need for explicit dependency mapping via `depends_on`, it can be tricky to spot these problems: Even if you get all of the resources dialed in to fix the build errors, Terraform doesn't know that `deployment` has to run last, so you might run the project, get that error, and check the GUI to find all green. This will be because Terraform attempted deploying the project moments before completing it.

Because the "deployment" resource can be tricky to use, especially while you're hammering details of your topology. I recommend you:
- set `blueprint_mutex_enabled = false` in the provider block
- skip the `apstra_blueprint_deployment` resource until the rest of your terraform is consistently rendering no build errors

The 4.2.1 issue boils down to: "some API endpoints have changed and we haven't caught up with them in the Terraform provider". You can see the versions known to work with each release [here](https://registry.terraform.io/providers/Juniper/apstra/latest/docs).

**Comment by chrismarget-j** [comment]
It looks like that should have worked.

Can you share `terraform state list` and `terraform state show apstra_datacenter_resource_pool_allocation.asn["leaf_asns"]`?

**Comment by viets2k** [comment]
<pre>
terraform state list
apstra_datacenter_blueprint.instantiation
apstra_datacenter_device_allocation.interface_map_assignment["l2_virtual_001_leaf1"]
apstra_datacenter_device_allocation.interface_map_assignment["l2_virtual_002_leaf1"]
apstra_datacenter_device_allocation.interface_map_assignment["l2_virtual_003_leaf1"]
apstra_datacenter_device_allocation.interface_map_assignment["l2_virtual_004_leaf1"]
apstra_datacenter_device_allocation.interface_map_assignment["spine1"]
apstra_datacenter_device_allocation.interface_map_assignment["spine2"]
apstra_datacenter_resource_pool_allocation.asn["leaf_asns"]
apstra_datacenter_resource_pool_allocation.asn["spine_asns"]
apstra_datacenter_resource_pool_allocation.ipv4["leaf_loopback_ips"]
apstra_datacenter_resource_pool_allocation.ipv4["spine_leaf_link_ips"]
apstra_datacenter_resource_pool_allocation.ipv4["spine_loopback_ips"]
</pre>
terraform state show 'apstra_datacenter_resource_pool_allocation.asn["leaf_asns"]'
# apstra_datacenter_resource_pool_allocation.asn["leaf_asns"]:
resource "apstra_datacenter_resource_pool_allocation" "asn" {
    blueprint_id = "534113df-6749-46ac-b5d6-745146da9fde"
    pool_ids     = [
        "Private-4200000000-4294967294",
    ]
    role         = "leaf_asns"
}
<pre>

</pre>

**Comment by viets2k** [comment]
sorry missed the pre

<pre>
terraform state show 'apstra_datacenter_resource_pool_allocation.asn["leaf_asns"]'
# apstra_datacenter_resource_pool_allocation.asn["leaf_asns"]:
resource "apstra_datacenter_resource_pool_allocation" "asn" {
    blueprint_id = "534113df-6749-46ac-b5d6-745146da9fde"
    pool_ids     = [
        "Private-4200000000-4294967294",
    ]
    role         = "leaf_asns"
}
</pre>

**Comment by chrismarget-j** [comment]
Cool.

We should also check whether that ASN pool ID is legit.

You can test that in the Apstra GUI at `Resources -> ASN Pools` and then clicking on any pool.

Then strip the trailing part of the URL and replace it with this pool ID: `Private-4200000000-4294967294`

**Comment by viets2k** [comment]
oh shame on me, I accidentially deleted the "Private-4200000000-4294967294" pool before and that's why it failed. If I use the pool "Private-64512-65534" it's working, and it's a bit confusing that the standard ressource using readable strings but everything else random ids.

I'm sorry for wasting your time. Not sure if there should be a warning, pool not found, but other than that it was a human error and you can close it.

Thanks for your support.

**Comment by chrismarget-j** [comment]
Hey, no problem!

I agree about the "friendly" ID strings. Very surprising that "baked in" resources get these IDs while others get random values.

A safer way to proceed here would be to use a data lookup based on a human-readable string, rather than assuming we "just know" the ID:

```hcl
data "apstra_asn_pool" "private" {
  name = "my pool name"    // <---- human readable name from the web UI - plus we get an error if it doesn't exist
}

locals {
  asn_pools = {
    leaf_asns  = [data.apstra_asn_pool.private.id] // <---- get the pool ID by reference
  }
}
```

**Comment by chrismarget-j** [comment]
Update on "Not sure if there should be a warning, pool not found":

Apstra engineering has agreed that server side validation of pool assignments is appropriate. We'll have it in a future release. Internally it's being tracked as AOS-42106
