### ISSUE TITLE
Inconsistent VNI value when adding/editing a Routing Zone

### ISSUE THREAD

**Issue by coterv** [Juniper/terraform-provider-apstra#598]
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.blueprints.apstra_datacenter_routing_zone.vrfs["MAIN_ALC2.I-MANO-CGExtCtl"], provider "provider[\"registry.terraform.io/juniper/apstra\"]" produced an unexpected new value: .vni: was cty.NumberIntVal(1.2000051e+07), but now
│ null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by chrismarget-j** [comment]
Closed by #599
