### ISSUE TITLE
How to support SONiC with `apstra_agent_profile` resource?

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#612]
The `apstra_agent_profile` resource currently only allows three values for the `platform` attribute:

- `junos`
- `eos`
- `nxos`

And it defaults to `junos`.

There's no provision for SONiC. Should there be?

In the web UI it is possible to omit this field altogether by select nothing from the dropdown box. This produces an Agent Profile with `""` in the `platform` field.

Should this be an option?

**Comment by rajagopalans** [comment]
Does a "" mean sonic?

**Comment by bwJuniper** [comment]
I dont think so, it just means "i didnt select one" you can manually specify user name / pw and not select one it will try to figure out what device it is and apply the correct agent.
