### ISSUE TITLE
resource  & data source to load /display network os Images into apstra

### ISSUE THREAD

**Issue by bwJuniper** [Juniper/terraform-provider-apstra#647]

**Comment by bwJuniper** [comment]
POST to /api/device-os/images-external

**Comment by chrismarget-j** [comment]
This seemed like a good idea when we were talking about just *the URL* of OS images.

Given the limited utility of approach, and the complications (never mind of non-declarative nature) of terraforming the *actual image*, I think this is a "won't do".

Closing for now. we can revisit if needed.
