### ISSUE TITLE
resource apstra_datacenter_routing_zone does not allocates Leaf Loopback ip's

### ISSUE THREAD

**Issue by Walter-Smet-at-delen** [Juniper/terraform-provider-apstra#672]
inherit from blueprint or create a resource apstra_datacenter_routing_zone_resource_pool_allocation

**Comment by Walter-Smet-at-delen** [comment]
creating a routing zone with this code:
~~~
resource "apstra_datacenter_routing_zone" "routing_zone" {
  name              = var.routing_zone_name
  blueprint_id      = apstra_datacenter_blueprint.this.id
  vlan_id           = var.routing_zone_vlan_id
  vni               = var.routing_zone_vni
}
~~~
does not allocates leaf loopback ip's.

possible solutions:
- add a parameter to apstra_datacenter_routing_zone
- inherit from blueprint
- foresee a resource apstra_datacenter_routing_zone_resource_pool_allocation

**Comment by chrismarget-j** [comment]
As in the Web UI, a resource pool needs to be allocated for assigning loopback addresses within each routing zone.

You can do this using the [`apstra_datacenter_resource_pool_allocation`](https://registry.terraform.io/providers/Juniper/apstra/latest/docs/resources/datacenter_resource_pool_allocation) resource with the optional `routing_zone_id` attribute:

```terraform
resource "apstra_datacenter_resource_pool_allocation" "routing_zone" {
  blueprint_id    = apstra_datacenter_blueprint.this.id
  routing_zone_id = apstra_datacenter_routing_zone.routing_zone.id
  role            = "leaf_loopback_ips"
  pool_ids        = [ apstra_ipv4_pool.something.id ]
}
```

Including `routing_zone_id` makes the `apstra_datacenter_resource_pool_allocation` resource behave the way you probably imagined `apstra_datacenter_routing_zone_resource_pool_allocation` would behave.

**Comment by Walter-Smet-at-delen** [comment]
Hello,

Thanks for the quick response. Exactly what I need!

Maybe you can add a notice in the documentation regarding this setting on:
https://registry.terraform.io/providers/Juniper/apstra/latest/docs/resources/datacenter_routing_zone
