### ISSUE TITLE
Nodename allocated to node are unknown

### ISSUE THREAD

**Issue by rajatmishra090** [Juniper/terraform-provider-apstra#685]
I am working apstra terraform for pod based design.
In a pod-based design, I am facing an issue with device allocation. The sequence in which pods are being created by Apstra is unknown, as a result, we are unable to determine which nodename will be assigned to which pod node, and the same applies to rack nodes.
I have multi pod design which consists of 4 pods.
Pod Untitled-5344528 has 2 rack
Pod Untitled-5353720 has 3 rack
Pod Untitled-3837048 has  3 rack
Pod Untitled-3847627 has 4 rack
 
Now in Terraform Apstra, we are not aware of which sequence pod creation will occur, which is causing us to be unable to fabricate the correct nodename which is required in ‘device allocation resource’ and there is no other way I am able to figure out nodename for a particular  node. The nodename is internal to Apstra and is being created on run.
 
 
I tested out a simple single pod-based arrangement with one pod and one rack, and it worked well.

pod based terraform file
[terraform_file](https://gist.github.com/rajatmishra090/27eec32c8e93837fcb2ac0a8ca33aab5)

**Comment by chrismarget-j** [comment]
#275 helped with this issue - we render pods in a predictable order now.

Long term: we should replace many maps in design API with lists. See, for example, #337 and #338.
