### ISSUE TITLE
Example is wrong for apstra_datacenter_connectivity_templates_assignment resource

### ISSUE THREAD

**Issue by williampincek47** [Juniper/terraform-provider-apstra#689]
Documentation error:

https://registry.terraform.io/providers/Juniper/apstra/latest/docs/resources/datacenter_connectivity_templates_assignment

The example usage shows the deprecated resource, apstra_datacenter_connectivity_template_assignment, instead of the new resource called apstra_datacenter_connectivity_templates_assignment.

**Comment by chrismarget-j** [comment]
Indeed.

I think we're missing an `s` in the example block.
