### ISSUE TITLE
apstra_datacenter_resource_pool_allocation role description

### ISSUE THREAD

**Issue by williampincek47** [Juniper/terraform-provider-apstra#691]
Hi,

I'd like to suggest to have the documentation for the apstra_datacenter_resource_pool_allocation resource to be updated to mention the possible roles that exist.  If you create this resource and specify a non-existent role, you get this error...

â”‚ Attribute role value must be one of: ["superspine_asns" "spine_asns" "leaf_asns" "access_asns" "generic_asns" "superspine_loopback_ips"
â”‚ "superspine_loopback_ips_ipv6" "spine_loopback_ips" "spine_loopback_ips_ipv6" "leaf_loopback_ips" "leaf_loopback_ips_ipv6" "access_loopback_ips"
â”‚ "spine_superspine_link_ips" "ipv6_spine_superspine_link_ips" "spine_leaf_link_ips" "ipv6_spine_leaf_link_ips" "access_l3_peer_link_link_ips"
â”‚ "leaf_leaf_link_ips" "leaf_l3_peer_links" "leaf_l3_peer_links_ipv6" "mlag_domain_svi_subnets" "mlag_domain_svi_subnets_ipv6" "vtep_ips"
â”‚ "evpn_l3_vnis" "virtual_network_svi_subnets" "virtual_network_svi_subnets_ipv6" "vni_virtual_network_ids" "to_generic_link_ips"
â”‚ "ipv6_to_generic_link_ips"], got: "steve"

Why should I have to learn the possible roles from an error message?  Also, the documentation should mention how the user would determine which role should be chosen.  I believe the only way to tell is to go to the UI and look for any resource allocation groups that are colored red.

Right now, none of the above information is mentioned.  It just says...

role - (String) Fabric Role (Apstra Resource Group Name)

Hope that helps,

Will Pincek

**Comment by chrismarget-j** [comment]
See updated docs for this resource here:

https://registry.terraform.io/providers/Juniper/apstra/0.59.1/docs/resources/datacenter_resource_pool_allocation#role
