### ISSUE TITLE
Proposal: `apstra_telemetry_service_registry_entry` rename `service_name` to `name`

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#724]
I think we should rename `service_name` to `name` in the `apstra_telemetry_service_registry_entry` resource and data source.

Reasons:

1. "service" is redundant. It's already a *service* registry entry.
2. The GUI uses both *service name* and *name* for this attribute, so it's not clear that one is preferred over the other.
3. `name` is consistent with our other resources.
4. The resource doesn't have an `id` attribute. With neither an `id` nor `name` attribute, Terraform's [`ObjectValueId()` function](https://github.com/hashicorp/terraform/blob/125cf53470a3e9ada9e1c79cb077c3ca36a06607/internal/command/format/object_id.go#L26C1-L62C1) won't find any identifier to use in user-facing output for this resource.

**Comment by rajagopalans** [comment]
I am fine with this. I didn't have a strong opinion, so I just used what was in the API.

**Comment by rajagopalans** [comment]
closed by #725
