### ISSUE TITLE
Potential issues with v0.63.0 with role name changes and ct assignments

### ISSUE THREAD

**Issue by michaelbhughes** [Juniper/terraform-provider-apstra#762]
## Summary
I upgraded from `v0.58.1` to `v0.63.0` of the provider and ran into two strange issues. One is related to the role name change for ipv6 roles, while the other seems unrelated. Details are below.

I am using Terraform `1.5.5` on `linux_amd64`.

### Issue 1: ct assignment context deadline exceeded on only two blueprints
![image](https://github.com/user-attachments/assets/26f31609-cd1a-49dc-a6f0-66cc4f91189b)

- I was using `v0.58.1` of the provider before updating to `v0.63.0` and validated that I did not experience this issue before updating.
- Does context deadline exceeded simply mean a timeout is being reach with the Apstra API?
- This issue did not appear on all my blueprints. Only two blueprints have this error appearing.

### Issue 2: the ipv6 pools want to be updated in-place for all the blueprints, the apply fails for this
![image](https://github.com/user-attachments/assets/c54cd9ca-b986-49cc-a042-e5febc71d81d)

- I successfully updated the `apstra_datacenter_resource_pool_allocation` resources with the role name changes.
- When I checked another job/tfstate that managed the resource pools, I saw that Terraform wanted to updated in-place the ipv6_pools; this is not an expected behaviour of this change.
- The tf code is below for this and it has no explicit dependencies or any implicit dependencies that may have triggered this update in-place.

```tf
resource apstra_ipv6_pool ipv6_pools {
    for_each    = var.ipv6_pools
    name        = each.value.name
    subnets     = each.value.subnets
}
```
- This issue appears on all blueprints.

## Next Steps
I would like help troubleshooting these two issues. Perhaps `v0.63.0` introduced a ct assignment bug? And the ipv6_pools should not be affected by the ipv6 role name change. Please help me investigate.

**Comment by chrismarget-j** [comment]
> Does context deadline exceeded simply mean a timeout is being reach with the Apstra API?

Yes. This correlates exactly with the `api_timeout` [provider configuration attribute](https://registry.terraform.io/providers/Juniper/apstra/latest/docs#api_timeout). I can't think of any reason this error should be related to the pool assignment change.

Is there any indication that this is repeatable vs. being a fluke?

> the ipv6 pools want to be updated in-place for all the blueprints

This is expected. Changing the `role` attribute is a change as far as Terraform is concerned, but once it's rendered into an API payload for Apstra, the result is exactly what's *already on Apstra*. So, we make the API call, and write the same value that's already there.

> the apply fails for this

Well, *that part* isn't expected!

We can discuss at your convenience tomorrow.

**Comment by michaelbhughes** [comment]
> Is there any indication that this is repeatable vs. being a fluke?

Yes, this is repeatable for the two blueprints that are experiencing this issue. I can demo this when we chat.

> Well, that part isn't expected!

I agree it's not expected for the `apstra_datacenter_resource_pool_allocation` and updating this resource worked without issue. What the issue is now is that the `apstra_ipv6_pool` resource wants to update in place, which is a separate resource, and this update fails stating you cannot update a pool that is in use even though Terraform doesn't show anything significant changing.

Looking forward to digging into these issues in our next chat.

**Comment by michaelbhughes** [comment]
The latest `v0.67.0` works! I no longer see the `context deadline exceeded` errors. Adding the return to the function that we looked at together was indeed the fix.

Also, the `APSTRA_API_TIMEOUT` env var is set properly now. Screenshot below.
![image](https://github.com/user-attachments/assets/1a759e53-73ab-4ecc-883c-1ebe0e397a43)

**Comment by chrismarget-j** [comment]
Right on! Thanks for following up.
