### ISSUE TITLE
The provider juniper/apstra does not support resource type "apstra_freeform_resource_generator".

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#777]
terraform plan

Error: Invalid resource type

 on 4_resource.tf line 23, in resource "apstra_freeform_resource_generator" "test_res_gen":
 23: resource "apstra_freeform_resource_generator" "test_res_gen" {

 The provider juniper/apstra does not support resource type "apstra_freeform_resource_generator".

**Comment by chrismarget-j** [comment]
Hello @ihadi581 thank you for opening this issue.

I don't think we've released support for resource generators quite yet. Do you see some indication that it should be available?

If you have an urgent need for it, we can probably expedite a release.

**Comment by ihadi581** [comment]
Hi @chrismarget-j i read on apstra GitHub they already done for resource generator but on terraform provider not supported. 
this link "https://github.com/Juniper/terraform-provider-apstra/blob/main/apstra/freeform/freeform_resource_generator.go"

what date release for resource generator?

**Comment by chrismarget-j** [comment]
Hi @ihadi581,

I've just released v0.68.0 with support for freeform resource generator resource and data source.

It should be hitting the mirrors over the next few minutes.

Would you mind dropping an email to terraform-provider-apstra@<*domain which starts with j*>.net to introduce yourself? As far as I know you're the first to use Freeform features, and if you're so keen to get new features, we'd like to be better in touch and make sure you're getting what you need out of the provider.

Thanks!

**Comment by ihadi581** [comment]
solved, after update to provider version 0.68.0
