### ISSUE TITLE
Error: error creating new System for External system

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#780]
i try create external system but got error:
Error: error creating new System

   with apstra_freeform_system.vmx_mpls,
  on 1_systems.tf line 104, in resource "apstra_freeform_system" "vmx_mpls":
 104: resource "apstra_freeform_system" "vmx_mpls" {
 
{"api_response":null,"config_blueprint_version":0,"errors":{"device_profile_id":"Device Profile is only applicable for systems with type \"internal\""},"error_code":422} - http response '' at
 'http://192.187.125.211:8443/api/blueprints/36b6a1db-b62a-41e5-82f8-df08bfa6eb77/generic-systems?async=full&async=full'

this example system.tf for external system

resource "apstra_freeform_system" "vmx_mpls" {
  blueprint_id      = "36b6a1db-b62a-41e5-82f8-df08bfa6eb77"
  name              = "vMX_MPLS"
  tags              = null
  type              = "external"
  hostname          = "vMX-MPLS"
  deploy_mode       = "undeploy"
  device_profile_id = "null"

}

**Comment by chrismarget-j** [comment]
At a quick glance, I guess `"null"` should be `null`.

**Comment by chrismarget-j** [comment]
This looks like a bug.

**Comment by chrismarget-j** [comment]
Version 0.68.1 should have better compatibility with `external` freeform systems.

**Comment by ihadi581** [comment]
after upgrade for this version, now is working
