### ISSUE TITLE
This is a bug in the provider, which should be reported in the provider's own issue tracker. for Creating link combination with resources generator Freeform

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#788]
after adding new link terraform respone erorr message with inconsistent result:

apstra_freeform_link.sp1_lf2: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to apstra_freeform_link.sp1_lf2, provider "provider[\"registry.terraform.io/juniper/apstra\"]" produced an unexpected new value: .endpoints["R2l1ncNiGlPZFj1LK30"].ipv4_address: was null, but now
│ cty.StringVal("192.168.1.2/30").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to apstra_freeform_link.sp1_lf2, provider "provider[\"registry.terraform.io/juniper/apstra\"]" produced an unexpected new value: .endpoints["hKEbtMQFyJXhlyUvsM0"].ipv4_address: was null, but now
│ cty.StringVal("192.168.1.1/30").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

but on UI apstra, success create link:
<img width="1603" alt="Screenshot 2024-08-14 at 14 03 37" src="https://github.com/user-attachments/assets/bb09b413-5974-4ad5-8ba6-6867d58d1dc6">

this example for tf file :
# Create a resource link to target all systems in the blueprint.
resource "apstra_freeform_link" "sp1_lf2" {
  blueprint_id = apstra_freeform_blueprint.dc1.id
  name         = "sp1_lf2"
  tags         = null
  endpoints    = {
        R2l1ncNiGlPZFj1LK30 = {
            interface_name    = "ge-0/0/0"
            ipv4_address      = null
            ipv6_address      = null
            tags              = null
            transformation_id = 1
       },
       hKEbtMQFyJXhlyUvsM0 = {
            interface_name    = "ge-0/0/0"
            ipv4_address      = null
            ipv6_address      = null
            tags              = null
            transformation_id = 1
            }
      }
}

**Comment by chrismarget-j** [comment]
Closed by #790
