### ISSUE TITLE
Documentation issue in `apstra_freeform_link`

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#791]
[This](https://github.com/Juniper/terraform-provider-apstra/blob/664944e469b0fe49704355f839fd8affb319147b/apstra/freeform/freeform_link.go#L82C1-L83C1) isn't clear. "Map keyed by what?"

Data source should `MarkdownDescription` should be similarly updated.

[The example](https://github.com/Juniper/terraform-provider-apstra/blob/main/examples/resources/apstra_freeform_link/example.tf) looks like a problem as well. `endpoints` there is a list or set, not a map.

**Comment by bwJuniper** [comment]
endpoints    = {
           4WBxH-fmNj1Q2eTr3aI =  {     
            interface_name    = "ge-0/0/0"
            ipv4_address      = "192.168.1.1/30"
            transformation_id = 1
            },
            TGSCjWX7SloVcAacyCQ = {     
            interface_name    = "ge-0/0/0"
            ipv4_address      = "192.168.1.2/30"
            transformation_id = 1
            }
      }
