### ISSUE TITLE
Error: Duplicate resource "apstra_freeform_resource" configuration

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#792]
I want to make the resource name the same but the terraform provider doesn't support it yet. 

this output from cli :
│ Error: Duplicate resource "apstra_freeform_resource" configuration
│ 
│   on 0_provider.tf line 379:
│  379: resource "apstra_freeform_resource" "vni" {
│ 
│ A apstra_freeform_resource resource named "vni" was already declared at 0_provider.tf:337,1-42. Resource names must be unique per type in each module.
╵
╷
│ Error: Duplicate resource "apstra_freeform_resource" configuration
│ 
│   on 0_provider.tf line 387:
│  387: resource "apstra_freeform_resource" "rt" {
│ 
│ A apstra_freeform_resource resource named "rt" was already declared at 0_provider.tf:345,1-41. Resource names must be unique per type in each module.
╵
this is expected resource can be created with same vni and rt name but different vlan group member:
vlan Internet.100:
<img width="1330" alt="image" src="https://github.com/user-attachments/assets/f5e6eb29-d3fc-4499-b9db-e47fa31c7034">

vlan blue.200
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/df9e6f16-f10d-4b6f-bb6b-55d55c87dbde">

**Comment by bwJuniper** [comment]
This may be a terraform limitation, as per the error "Resource names must be unique per type in each module." you may need to create a terraform "module" here (make a directory and place the TF files in the directory) to be allowed to create the same resource name ... I do not believe that we have any restrictions on what the name of the resource can be, at least there is none in our code.

**Comment by ihadi581** [comment]
solved after add number of name module. this sample tf file:
```

resource "apstra_freeform_resource" "Internet_100" {
  blueprint_id  = apstra_freeform_blueprint.dc1.id
  name          = "Internet_100"
  type          = "integer"
  group_id      = apstra_freeform_resource_group.Internet_100.id
  integer_value = "100"
  allocated_from = apstra_freeform_allocation_group.vlan_allocation.id
}
resource "apstra_freeform_resource" "vni" {
  blueprint_id  = apstra_freeform_blueprint.dc1.id
  name          = "vni"
  type          = "integer"
  group_id      = apstra_freeform_resource_group.Internet_100.id
  integer_value = "100"
  allocated_from = apstra_freeform_allocation_group.vni_allocation.id
}
resource "apstra_freeform_resource" "rt" {
  blueprint_id  = apstra_freeform_blueprint.dc1.id
  name          = "rt"
  type          = "integer"
  group_id      = apstra_freeform_resource_group.Internet_100.id
  integer_value = "8000001"
  allocated_from = apstra_freeform_allocation_group.rt_allocation.id
}


resource "apstra_freeform_resource_group" "blue_200" {
  blueprint_id = apstra_freeform_blueprint.dc1.id
  name         = "blue_200"
  parent_id    = apstra_freeform_resource_group.vlans.id
  data = jsonencode({
    "bgp_irb": "disable",
    "vrf_name": "blue",
    "peer_ipv4_loopback": "",
    "bfd_minimum": "",
    "peer_asn": "",
    "bfd_multiplier": "",
    "l3": "enable",
    "static_route_irb": "disable",
    "mode_style": "ent-style"
  })
}

resource "apstra_freeform_resource" "blue_200" {
  blueprint_id  = apstra_freeform_blueprint.dc1.id
  name          = "blue_200"
  type          = "integer"
  group_id      = apstra_freeform_resource_group.blue_200.id
  integer_value = "200"
  allocated_from = apstra_freeform_allocation_group.vlan_allocation.id
}
resource "apstra_freeform_resource" "vni1" {
  blueprint_id  = apstra_freeform_blueprint.dc1.id
  name          = "vni"
  type          = "integer"
  group_id      = apstra_freeform_resource_group.blue_200.id
  integer_value = "200"
  allocated_from = apstra_freeform_allocation_group.vni_allocation.id
}
resource "apstra_freeform_resource" "rt1" {
  blueprint_id  = apstra_freeform_blueprint.dc1.id
  name          = "rt"
  type          = "integer"
  group_id      = apstra_freeform_resource_group.blue_200.id
  integer_value = "8000000"
  allocated_from = apstra_freeform_allocation_group.rt_allocation.id
}

```
