### ISSUE TITLE
Error: Conflicting Attributes when create apstra_freeform_resource for ipv4

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#793]
after trying create resource ipv4 found error Conflicting Attributes:

this sample tf file first condition:
```
resource "apstra_freeform_resource" "network" {
  blueprint_id   = apstra_freeform_blueprint.dc1.id
  name           = "network"
  type           = "ipv4"
  group_id       = apstra_freeform_resource_group.Internet_100.id
  allocated_from = apstra_freeform_allocation_group.vrf_internet_allocation.id
  ipv4_value     = "192.168.159.0/24"
  integer_value  = "24"
}
```
and get error :

```
│ Error: Conflicting Attributes
│ 
│   with apstra_freeform_resource.network,
│   on 0_provider.tf line 496, in resource "apstra_freeform_resource" "network":
│  496: resource "apstra_freeform_resource" "network" {
│ 
│ `integer_value` must not be set when `ipv4_value` is set and `type` is set to "ipv4"
```
and second condition remove "integer_value  = "24"
```
resource "apstra_freeform_resource" "network" {
  blueprint_id   = apstra_freeform_blueprint.dc1.id
  name           = "network"
  type           = "ipv4"
  group_id       = apstra_freeform_resource_group.Internet_100.id
  allocated_from = apstra_freeform_allocation_group.vrf_internet_allocation.id
  ipv4_value     = "192.168.159.0/24"
}
```
get erorr :
```
Plan: 8 to add, 0 to change, 8 to destroy.
╷
│ Error: Conflicting Attributes
│ 
│   with apstra_freeform_resource.network,
│   on 0_provider.tf line 496, in resource "apstra_freeform_resource" "network":
│  496: resource "apstra_freeform_resource" "network" {
│ 
│ `integer_value` is used to indicate the Subnet Prefix Length. It must be set when `allocated_from` is set and `type` is set to "ipv4"
```

**Comment by bwJuniper** [comment]
It seems you have selected "allocated_from" here , which means you want to automatically allocate a resource from a pool, but you have also specified a value directly.  I think you want one or the other not both.

resource "apstra_freeform_resource" "network" {
  blueprint_id   = apstra_freeform_blueprint.dc1.id
  name           = "network"
  type           = "ipv4"
  group_id       = apstra_freeform_resource_group.Internet_100.id
  allocated_from = apstra_freeform_allocation_group.vrf_internet_allocation.id
  ipv4_value     = "192.168.159.0/24"
  integer_value  = "24"
}

**Comment by ihadi581** [comment]
ok understand but if type with "integer" this resource normally working this sample if using type integer and if only use manual create without allocation from this resource normally working. this sample for integer type :

```
resource "apstra_freeform_resource" "blue_200" {
  blueprint_id  = apstra_freeform_blueprint.dc1.id
  name          = "blue_200"
  type          = "integer"
  group_id      = apstra_freeform_resource_group.blue_200.id
  integer_value = "200"
  allocated_from = apstra_freeform_allocation_group.vlan_allocation.id
}
```

i think from UI apstra if i associate to resource pool they need put Subnet Prefix Length also value. but in terraform module only have ipv4 value not have Subnet Prefix Length.

**Comment by bwJuniper** [comment]
Correct, subnetprefixlen is in the UI, but to make the provider implementation cleaner, we just used the `integer_value` field for the subnet prefix length ... so I would assume that 

```
resource "apstra_freeform_resource" "network" {
  blueprint_id   = apstra_freeform_blueprint.dc1.id
  name           = "network"
  type           = "ipv4"
  group_id       = apstra_freeform_resource_group.Internet_100.id
  allocated_from = apstra_freeform_allocation_group.vrf_internet_allocation.id
  integer_value     = 24
}
```
would work.

**Comment by ihadi581** [comment]
still not work if i using you susgest module resource : 
```
terraform plan
╷
│ Error: Missing required attribute
│ 
│   with apstra_freeform_resource.network,
│   on 0_provider.tf line 455, in resource "apstra_freeform_resource" "network":
│  455: resource "apstra_freeform_resource" "network" {
│ 
│ Either `allocated_from` or `ipv4_value` must also be set when `type` is set to "ipv4"
```

**Comment by bwJuniper** [comment]
This is a bug it seems. Somehow we are specifying `allocated_from` but it is not getting set ... we will look into this.

**Comment by chrismarget-j** [comment]
Doesn't [this error](https://github.com/Juniper/terraform-provider-apstra/issues/793#issuecomment-2289135134) make sense in this context? 

> Either `allocated_from` or `ipv4_value` must also be set when `type` is set to "ipv4"

When creating an IPv4 resource (a subnet), you must specifiy one of these options:
1. the exact subnet you want (CIDR notation in the `string_value` attribute)
1. both of these:
  - the size of subnet (integer_value)
  - a source to pull the subnet from (allocated_from)

It's possible I'm not following what's going on here.

**Comment by bwJuniper** [comment]
@chrismarget-j  and I worked through the validation logic and found some issues.
