### ISSUE TITLE
add new feature `Config-Template` assignment for `apstra_freeform_config_template`

### ISSUE THREAD

**Issue by ihadi581** [Juniper/terraform-provider-apstra#835]
Hi,

Currntly terrafrom provider not already assignment config template to system.

if i check in api apstra this example :

<img width="1847" alt="image" src="https://github.com/user-attachments/assets/e4d207e0-49d3-40fe-b42b-914f379f64ca">

SSXOei_RYGUEpTDeAKg : this system id
j0LBK2RzArOx5ulaT6A : this id for template.

if see on apstra freefrom UI, after import device from terrafrom by default config template not assigment:
<img width="1778" alt="image" src="https://github.com/user-attachments/assets/2df5e90a-dced-42a5-82e1-e94f30109cf8">

our use case terraform can be assign template also to device system internal

**Comment by chrismarget-j** [comment]
Prioritizing these features would be easier if we understood your project, timeline, and so forth.

Would you please send an email so we can set up a time to discuss? terraform-provider-apstra@junXXremovethisXXiper.net

**Comment by ihadi581** [comment]
hi, i already email to [terraform-provider-apstra@junXXremovethisXXiper.net](mailto:terraform-provider-apstra@junXXremovethisXXiper.net), we can discus in detail on call.

**Comment by bwJuniper** [comment]
Hi there, 

You do realize that you do not need to assign config templates to the device to be able to use them. They can be "not assigned" and you can still include them / use them in the devices.  We demonstrated this in the Freeform Labs in cloudlabs.

If you still need it, please explain the use case in detail for us. (Maybe you want to use specific config template for specific devices? in that case you could just name the CT on a per device basis and include them via a %include <devicename_ct.jinja> %)

**Comment by bwJuniper** [comment]
/api/blueprints/{blueprint_id}/config-templates-assignments
