### ISSUE TITLE
Improve example for `apstra_ datacenter_ip_link_addressing` resource

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#846]
https://registry.terraform.io/providers/Juniper/apstra/latest/docs/resources/datacenter_ip_link_addressing

Example should explain how to discover link ID.

**Comment by michaelbhughes** [comment]
To clarify, we would like more information on how to provide the link_id dynamically via a data source of a variable.

![image](https://github.com/user-attachments/assets/e4d5370b-bf85-4636-88df-c723567d1195)
