### ISSUE TITLE
Eliminate use of unkeyed fields in struct literals

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#89]
Most (all?) graph DB query code uses unkeyed fields in struct literals.

This isn't a safe pattern when used across an import boundary.

**Comment by rajagopalans** [comment]
Looks good to me,
However, I am unsure why specifying the keys is required. Will Golang not fill out the fields in order?

**Comment by chrismarget-j** [comment]
As written, the code works fine. But there's no contract about the order of fields in the struct, and the struct is part of an import.

As I understand it, using un-keyed fields is reasonable/safe/acceptable when the struct is defined in the same package.

It becomes less reasonable/safe when it's imported.

It's not so bad when we control both ends (we do), but `go vet` is complaining about it and "fixing" it seemed like the right thing to do.
