### ISSUE TITLE
Changing CT primitive elements has unintended downstream effects

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#993]
The current Connectivity Template resource model tracks *primitives* (the grey boxes in the CT web UI) as a *set* of terraform objects:

```terraform
resource "apstra_datacenter_connectivity_template_interface" "example" {
  blueprint_id = "<something>"
  name         = "Two VLANs"
  virtual_network_singles = [ # This is a SET
    { # Set element
      name = "a"
      tagged = true
      virtual_network_id = "11111111-1111-1111-1111-111111111111"
    },
    { # Set element
      name = "b"
      tagged = true
      virtual_network_id = "22222222-2222-2222-222222222222"
    },
  ]
}
```

Because set elements are identified by their value, any change to a set element, like changing `name = "a"` to `name = "A"`, causes that element to be recognized by terraform as a *different set element*. The old one has been removed, and a new one has been added to the set. There's no capability to recognize a *modified element*.

This results in replacement of the Apstra CT *primitive* (the grey box), which is a change that has implications for places that the CT has been applied:

- In the case of IP Link CT primitives, logical link graph nodes may be replaced, leading to loss of addresses assigned to them.
- In the case of BGP peering CTs, protocol session graph nodes may be replaced, leading to loss of BGP Policies applied to them.

Proposal:

Change the terraform schema for CT resources so that primitive objects are a *map*, rather than a *set*. The configuration above then becomes:

```terraform
resource "apstra_datacenter_connectivity_template_interface" "example" {
  blueprint_id = "<something>"
  name         = "Two VLANs"
  virtual_network_singles = { # This is a MAP
    a = { # The name ("a") is now the map key
      tagged = true
      virtual_network_id = "11111111-1111-1111-1111-111111111111"
    },
    b = { # The name ("b") is now the map key
      tagged = true
      virtual_network_id = "22222222-2222-2222-222222222222"
    },
  }
}
```

This will be a user-impacting change because of the new schema. Any users who have adopted these CT resources (released 2024-08-26) will need to adapt their configuration to match the map schema.

**Comment by ciroiriarte** [comment]
Would it be possible to provide another example for the provider documentation?. I'm currently splitting hairs trying to make "apstra_datacenter_connectivity_template_interface"+virtual_network_multiples work on 0.79.0

**Comment by grahamneville** [comment]
I too would like to see BGP Generic System examples, it seems to be nested under ip_links but when I attempt that I get an IP Link CT and not a BGP Generic System.
