### ISSUE TITLE
`apstra_blueprint_iba_dashboard` resource not compatible with current SDK

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#994]
The `grid` attribute  (two-dimensional slice of widget IDs) is no longer IDs. 2D slice of widget data objects now?

Looks like there's also a problem with `IbaWidgetData.Type`

**Comment by rajagopalans** [comment]
Yes.
This is why the apstra-go-sdk dashboard api is not compatible with anything lower than 5.0.
Anyone using the terraform provider for dashboards need to wait for the provider to be updated to match with 5.0 or use the earlier provider for older versions.

**Comment by rajagopalans** [comment]
At least that is how I *think* I have set the compatibility strings :-)

**Comment by chrismarget-j** [comment]
We need to do something about it in the provider project because I can't build the provider using the current SDK.

**Comment by rajagopalans** [comment]
Give me some time, I will disable this in the provider.

**Comment by chrismarget-j** [comment]
Yep, not an emergency.

If we're pulling those resources/data source from the provider for the time being, that's okay.

The files I had to butcher to get it to compile are:

- `apstra/data_source_blueprint_iba_widget.go`
- `apstra/data_source_blueprint_iba_widgets.go`
- `apstra/iba/dashboard.go`
- `apstra/iba/widget.go`
- `apstra/resource_blueprint_iba_widget.go`

**Comment by chrismarget-j** [comment]
Closed by #995
